package com.github.jlgrock.informatix.workmanager.domain.assignment
import com.github.jlgrock.informatix.workmanager.domain.attachment.AttachmentDTO
import com.github.jlgrock.informatix.workmanager.domain.useraccount.UserAccountDTO
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
/**
 *
 */
@ToString
@EqualsAndHashCode
class AssignmentDTO {

    int id

    UserAccountDTO userAccount

    int numberOfRecords

    AttachmentDTO original

    boolean completedExists

    Double billableHours

    boolean isAutoGenerated

    AssignmentStatus status

    AssignmentDTO(Assignment assignmentIn) {
        if (assignmentIn == null) {
            return
        }
        id = assignmentIn.id
        if (assignmentIn.userAccount != null) {
            userAccount = new UserAccountDTO(assignmentIn.userAccount)
        }
        numberOfRecords = assignmentIn.numberOfRecords
        if (assignmentIn.original != null) {
            original = new AttachmentDTO(assignmentIn.original)
        }
        if (assignmentIn.completed != null && assignmentIn.completed.size() > 0) {
            completedExists = true
        }
        billableHours = assignmentIn.billableHours
        isAutoGenerated = assignmentIn.isAutoGenerated
        status = assignmentIn.status
    }
}
