databaseChangeLog:
    - include:
        file: classpath:config/liquibase/changelog/00000000000000_initial_schema.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006153810_added_entity_User.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006153820_added_entity_Authorities.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006153830_added_entity_PersistentToken.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006153834_added_entity_VerificationTokens.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006153835_added_entity_PersistentAuditEvents.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006153838_added_entity_Attachment.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006154733_added_entity_Batch.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006154735_added_entity_Assignments.yaml
        relativeToChangelogFile: false
    - include:
        file: classpath:config/liquibase/changelog/20151006154740_bootstrap.yaml
        relativeToChangelogFile: false
