databaseChangeLog:
    - property:
        name: now
        value: now()
        dbms: mysql,h2
    - property:
        name: now
        value: current_timestamp
        dbms: postgresql
    - property:
        name: now
        value: sysdate
        dbms: oracle
    - property:
        name: autoIncrement
        value: true
        dbms: mysql,h2,postgresql
    - property:
        name: autoIncrement
        value: false
        dbms: oracle
    - changeSet:
        id: 2
        author: jlgrock
        changes:
            - createTable:
                tableName: user_accounts
                columns:
                    - column:
                        name: id
                        type: bigint
                        autoIncrement: ${autoIncrement}
                        constraints:
                            primaryKey: true
                            primaryKeyName: pk_user_accounts
                    - column:
                        name: login
                        type: varchar(50)
                        constraints:
                            unique: true
                            nullable: false
                    - column:
                        name: password
                        type: varchar(60)
                    - column:
                        name: first_name
                        type: varchar(50)
                    - column:
                        name: last_name
                        type: varchar(50)
                    - column:
                        name: email
                        type: varchar(100)
                        constraints:
                            unique: true
                    - column:
                        name: activated
                        type: boolean
                        value: false
                        constraints:
                            nullable: false
                    - column:
                        name: lang_key
                        type: varchar(5)
                    - column:
                        name: activation_key
                        type: varchar(20)
                    - column:
                        name: reset_key
                        type: varchar(20)
                    - column:
                        name: created_by
                        type: varchar(50)
                        constraints:
                            nullable: false
                    - column:
                        name: created_date
                        type: timestamp
                        defaultValueComputed: ${now}
                        constraints:
                            nullable: false
                    - column:
                        name: reset_date
                        type: timestamp
                        constraints:
                            nullable: true
                    - column:
                        name: last_modified_by
                        type: varchar(50)
                    - column:
                        name: last_modified_date
                        type: timestamp
            - createIndex:
                indexName: idx_user_login
                tableName: user_accounts
                unique: true
                column:
                    name: login
                    type: varchar(50)
            - createIndex:
                indexName: idx_user_email
                tableName: user_accounts
                unique: true
                column:
                    name: email
                    type: varchar(100)

