databaseChangeLog:
    - property:
        name: autoIncrement
        value: true
        dbms: mysql,h2,postgresql
    - property:
        name: autoIncrement
        value: false
        dbms: oracle
    - changeSet:
        id: 6
        author: jlgrock
        changes:
            - createTable:
                tableName: persistent_audit_events
                columns:
                    - column:
                        name: id
                        type: bigint
                        autoIncrement: ${autoIncrement}
                        constraints:
                            primaryKey: true
                            nullable: false
                            primaryKeyName: pk_persistent_audit_events
                    - column:
                        name: principal
                        type: varchar(255)
                        constraints:
                            nullable: false
                    - column:
                        name: event_date
                        type: timestamp
                    - column:
                        name: event_type
                        type: varchar(255)
            - createIndex:
                indexName: idx_persistent_audit_events
                tableName: persistent_audit_events
                columns:
                    - column:
                        name: principal
                        type: varchar(255)
                    - column:
                        name: event_date
                        type: timestamp

            - createTable:
                tableName: persistent_audit_events_data
                columns:
                    - column:
                        name: persistent_audit_event_id
                        type: bigint
                        constraints:
                            nullable: false
                            references: persistent_audit_events(id)
                            foreignKeyName: fk_persistent_audit_event_id
                    - column:
                        name: name
                        type: varchar(255)
                        constraints:
                            nullable: false
                    - column:
                        name: value
                        type: varchar(255)
            - addPrimaryKey:
                columnNames: persistent_audit_event_id, name
                tableName: persistent_audit_events_data
                constraintName: pk_persistent_audit_events_data
            - createIndex:
                indexName: idx_persistent_audit_event_data
                tableName: persistent_audit_events_data
                unique: false
                columns:
                    - column:
                        name: persistent_audit_event_id
                        type: bigint
